[package]
name = "toipe"
version = "0.1.0"
edition = "2021"
default-run = "toipe"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
termion = "1.5.6"
rand = "0.8.4"
bisection = "0.1.0"
